name: Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'production'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.NPM_TOKEN }}
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_VAL")):
            print(q)
            data.write(q)
        shell: python
